apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daylight-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/Blvck-roz/gitops-argocd.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

