apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daylight-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Blvck-roz/gitops-argocd.git'
    targetRevision: HEAD
    path: '.'  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: daylight-app-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
