apiVersion: v1
kind: Service
metadata:
  name: daylight-app-service
  namespace: daylight-app
spec:
  selector:
    app: daylight-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
